### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by LukaBis** [LukaBis/Ri-Event#81]
**Description:**

Adding main image to the README. Below image add badges for npm version, php, laravel version.
Find out how to add MIT licence to the rpoject and then add MIT badge.

How to add badges: https://stackoverflow.com/questions/49960254/how-can-i-get-colored-keyword-labels-in-readme-md-on-github
Example of how readme should look like: https://github.com/reactstrap/reactstrap

**Acceptance criteria:**

Added main image. Added badges for php, laravel, npm and MIT. MIT licence added to the proejct.

**Comment by PatrikPaunovic** [comment]
Task#51
Added image and badges
